spring:
  application:
    name: app
  profiles:
    default: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  output:
    ansi:
      enabled: always