logging:
  level:
    root: INFO
    web: DEBUG
    org:
      springframework:
        security: DEBUG
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
  hikari:
    shutdown-on-exit: false
    leak-detection-threshold: 2000
  h2:
    console:
      enabled: true
#  jpa:
#    hibernate:
#      ddl-auto: update
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem